name: run-tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 7.2, 7.3, 7.4, 8.0 ]
        laravel: [ 6.*, 7.*, 8.* ]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: 6.*
            testbench: 4.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 8.*
            testbench: 6.*
        exclude:
          - laravel: 7.*
            php: 7.2
          - laravel: 8.*
            php: 7.2
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, redis
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests - phpredis
        run: vendor/bin/phpunit
        env:
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}

      - name: Execute tests - predis
          run: vendor/bin/phpunit -c phpunit_predis.xml
          env:
            REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
